# Generated by Django 5.1 on 2024-11-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('storage_instructions', models.TextField(blank=True)),
                ('packaging', models.CharField(blank=True, max_length=255)),
                ('fragrance_type', models.CharField(blank=True, max_length=255)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ingredients', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('fragrance', models.CharField(blank=True, max_length=255)),
                ('usage_instructions', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_management.product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.subcategory'),
        ),
    ]
